apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: default  # Change if your app is deployed in another namespace
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
    - name: http
      port: 5000       # The port that the Service exposes
      targetPort: 5000 # The port your container listens on
      protocol: TCP
