version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gym_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gymdb
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: nutzkiller/gym:latest
    container_name: gym_web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gymdb

volumes:
  db_data:
