version: '3.8'  # Specify Docker Compose version

services:
  web:
    build: .
    container_name: gym_web
    restart: always
    ports:
      - "5000:5000"                        # Exposes Flask app on host port 5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}           # Replace with a strong, secure key
    networks:
      - gym_network
    volumes:
      - .:/app                             # Mounts project directory (optional for development)

networks:
  gym_network:
    driver: bridge                        # Uses Docker's default bridge driver
