version: '3.8'

services:
  web:
    image: nutzkiller/gym:latest
    container_name: gym_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - gym_network
    volumes:
      - .:/app

networks:
  gym_network:
    driver: bridge
