version: '3.8'  # Specify Docker Compose version

services:
  web:
    build: .
    container_name: gym_web
    restart: always
    ports:
      - "5000:5000"                # Expose Flask on host port 5000
    environment:
      # Update this line to your actual Cloud SQL public IP
      - DATABASE_URL=mysql+pymysql://postgres:password@CLOUD_SQL_IP:3306/GYM

      - SECRET_KEY=Kanao159632!!   # Replace with a strong, secure key
    networks:
      - gym_network
    volumes:
      - .:/app                     # Mount project directory (optional for dev)

# We no longer define the local MySQL container (db).
# The Flask app points to Cloud SQL, so no local DB needed.

networks:
  gym_network:
    driver: bridge
