apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-deployment
  namespace: gym-namespace
spec:
  replicas: 1  # Single replica to stay within Free Tier
  selector:
    matchLabels:
      app: gym
  template:
    metadata:
      labels:
        app: gym
    spec:
      containers:
        - name: gym-container
          image: nutzkiller/gym:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: gym-config
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gym-secret
                  key: SECRET_KEY
          resources:
            requests:
              memory: "256Mi"  # Minimum memory guaranteed
              cpu: "250m"       # Minimum CPU guaranteed (0.25 CPU core)
            limits:
              memory: "512Mi"  # Maximum memory allowed
              cpu: "500m"       # Maximum CPU allowed (0.5 CPU core)
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
