apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gym.fullname" . }}-config  # ConfigMap name using fullname helper
  labels:
    app: {{ include "gym.name" . }}              # Label for the app
data:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}  # Database URL configuration
