apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gym.fullname" . }}-deployment
  labels:
    app: {{ include "gym.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gym.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gym.name" . }}
      annotations:
        redeploy-timestamp: "{{ now | quote }}"
    spec:
      containers:
        - name: gym-container
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.databaseUrl | quote }}
            - name: SECRET_KEY
              value: {{ .Values.secretKey | quote }}
          resources:
            requests:
              memory: "{{ .Values.memoryRequest }}"
              cpu: "{{ .Values.cpuRequest }}"
            limits:
              memory: "{{ .Values.memoryLimit }}"
              cpu: "{{ .Values.cpuLimit }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessInitialDelay }}
            periodSeconds: {{ .Values.readinessPeriod }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessInitialDelay }}
            periodSeconds: {{ .Values.livenessPeriod }}
