apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gym.fullname" . }}-secret
  labels:
    app: {{ include "gym.name" . }}
type: Opaque
stringData:
{{- toYaml .Values.secret.stringData | nindent 2 }}
