apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gym.fullname" . }}-secret  # Secret name using fullname helper
  labels:
    app: {{ include "gym.name" . }}              # Label for the app
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretKey | quote }}     # Secret key value
