apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gym.fullname" . }}-secret
  labels:
    app: {{ include "gym.name" . }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretKey | quote }}
