apiVersion: v1
kind: Service
metadata:
  name: {{ include "gym.fullname" . }}-service
  labels:
    app: {{ include "gym.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "gym.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
