apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.6.7
        ports:
        - containerPort: 8080
        command: ["argocd-server"]
        args: ["--staticassets", "/shared/app"]
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
