replicaCount: 1

# Combine image repository, tag, and pullPolicy into one value
image: "nutzkiller/gym:latest"
imagePullPolicy: IfNotPresent

containerPort: 5000

# Instead of nested configMap and secret objects, define keys directly
databaseUrl: ""
secretKey: ""

# Resources and probes can be hardcoded in the template if they rarely change,
# or you can flatten them here:
memoryRequest: "512Mi"
cpuRequest: "250m"
memoryLimit: "1Gi"
cpuLimit: "500m"

readinessInitialDelay: 5
readinessPeriod: 10
livenessInitialDelay: 15
livenessPeriod: 20

serviceType: LoadBalancer
servicePort: 5000
