apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  additional-scrape-configs.yaml: |
    - job_name: 'gym_app'
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: ['gym-gym-service.gym-namespace.svc.cluster.local:5000']
