apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: grafana
    targetRevision: "6.60.2"  # This version works for you
    helm:
      values: |
        service:
          type: LoadBalancer
          port: 3000
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus.monitoring.svc.cluster.local:9090
                isDefault: true
                editable: false
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.monitoring.svc.cluster.local:3100
                editable: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
