apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki
    targetRevision: "2.8.0"  # Use a valid version from the Loki repo
    helm:
      values: |
        service:
          type: LoadBalancer
          port: 3100
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
