name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository code
      - name: Check out main repository
        uses: actions/checkout@v3

      # Step 2: Clone the Terraform State Repository
      - name: Clone Terraform State Repository
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/NutzKiller/TF.git
          echo "Cloned NutzKiller/TF repository."

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # Step 4: Create GCP credentials file
      - name: Create GCP credentials file
        run: |
          mkdir -p terraform
          echo "${{ secrets.GCP_CREDENTIALS_FILE_B64 }}" | base64 --decode > terraform/gcp_credentials.json

      # Debug: Check GCP credentials file (Optional - Remove or Secure After Verification)
      - name: Debug GCP credentials file
        run: |
          echo "Contents of GCP credentials file (first 100 characters):"
          head -c 100 terraform/gcp_credentials.json
          echo "Validating JSON formatting:"
          jq . terraform/gcp_credentials.json || { echo "Invalid JSON!"; cat terraform/gcp_credentials.json; exit 1; }

      # Step 5: Sync Terraform State from NutzKiller/TF Repository
      - name: Sync Terraform State from NutzKiller/TF Repository
        run: |
          if [ -f TF/terraform_state/terraform.tfstate ]; then
            mv TF/terraform_state/terraform.tfstate terraform/terraform.tfstate
            echo "Terraform state pulled from NutzKiller/TF repository."
          else
            echo "No existing Terraform state found in NutzKiller/TF repository. Proceeding with empty state."
          fi

      # Step 6: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key_file: terraform/gcp_credentials.json
          export_default_credentials: true

      # Step 7: Apply Terraform Configuration
      - name: Apply Terraform Configuration
        working-directory: terraform
        env:
          TF_VAR_GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          TF_VAR_GCP_REGION: ${{ secrets.GCP_REGION }}
          TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TF_VAR_MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

      # Step 8: Configure kubectl to connect to GKE
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: gym-cluster
          location: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Step 9: Apply Kubernetes Manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Step 10: Retrieve External IP of the Service
      - name: Retrieve External IP
        id: get_ip
        run: |
          echo "Waiting for LoadBalancer IP..."
          for i in {1..30}; do
            EXTERNAL_IP=$(kubectl get svc gym-service -n gym-namespace -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [ -n "$EXTERNAL_IP" ]; then
              echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
              echo "External IP: $EXTERNAL_IP"
              break
            fi
            echo "Attempt $i: External IP not assigned yet. Retrying in 10 seconds..."
            sleep 10
          done

          if [ -z "$EXTERNAL_IP" ]; then
            echo "Failed to retrieve External IP."
            exit 1
          fi

      # Step 11: Output the External IP
      - name: Output External IP
        run: |
          echo "The application is accessible at http://${{ env.EXTERNAL_IP }}"

      # Step 12: Wait for 300 seconds (e.g., to allow services to initialize)
      - name: Wait for 300 seconds
        run: |
          echo "Waiting for 300 seconds..."
          sleep 300

      # Step 13: Destroy Terraform Configuration
      - name: Destroy Terraform Configuration
        working-directory: terraform
        env:
          TF_VAR_GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          TF_VAR_GCP_REGION: ${{ secrets.GCP_REGION }}
          TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TF_VAR_MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          terraform destroy -auto-approve

      # Step 14: Push Updated Terraform State to NutzKiller/TF Repository
      - name: Push Updated Terraform State to NutzKiller/TF Repository
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          if [ -f terraform/terraform.tfstate ]; then
            mv terraform/terraform.tfstate TF/terraform_state/terraform.tfstate
            cd TF

            git config --global user.email "yuvalshmuely8@gmail.com"
            git config --global user.name "NutzKiller"

            git add terraform_state/terraform.tfstate
            git commit -m "Update Terraform state file after destroy" || echo "No changes to commit."
            git push origin main
          else
            echo "No Terraform state file found to push. Skipping this step."
          fi
