name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository code
      - name: Check out main repository
        uses: actions/checkout@v3

      # Step 2: Clone the Terraform State Repository
      - name: Clone Terraform State Repository
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/NutzKiller/TF.git
          echo "Cloned NutzKiller/TF repository."

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # Step 4: Create GCP credentials file
      - name: Create GCP credentials file
        run: |
          mkdir -p terraform
          echo "${{ secrets.GCP_CREDENTIALS_FILE_B64 }}" | base64 --decode > terraform/gcp_credentials.json

      # Step 5: Sync Terraform State from NutzKiller/TF Repository
      - name: Sync Terraform State from NutzKiller/TF Repository
        run: |
          mkdir -p terraform/terraform_state
          if [ -f TF/terraform_state/terraform.tfstate ]; then
            cp TF/terraform_state/terraform.tfstate terraform/terraform_state/terraform.tfstate
            echo "Terraform state pulled from NutzKiller/TF repository."
          else
            echo "No existing Terraform state found in NutzKiller/TF repository. Proceeding with empty state."
          fi

      # Step 6: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key_file: terraform/gcp_credentials.json
          export_default_credentials: true

      # Step 7: Apply Terraform Configuration
      - name: Apply Terraform Configuration
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "gcp_credentials.json"
          TF_VAR_GCP_CREDENTIALS_FILE: "gcp_credentials.json"
          TF_VAR_GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          TF_VAR_GCP_REGION: ${{ secrets.GCP_REGION }}
          TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TF_VAR_MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

      # Step 8: Configure kubectl to connect to GKE
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: gym-cluster
          location: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: terraform/gcp_credentials.json
     
      # Step 9: Create Namespace (if it doesn't exist)
      - name: Create Namespace
        run: |
          kubectl create namespace gym-namespace || true

      # Step 10: Inject GitHub Secrets into Kubernetes (DYNAMIC SECRETS)
      - name: Inject GitHub Secrets into Kubernetes
        run: |
          echo "Deleting old secrets and configmaps to avoid stale values..."
          kubectl delete secret gym-secret -n gym-namespace --ignore-not-found
          kubectl delete configmap gym-config -n gym-namespace --ignore-not-found

          echo "Creating new secrets and configmaps from GitHub Actions Secrets..."
          kubectl create secret generic gym-secret \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -n gym-namespace --dry-run=client -o yaml | kubectl apply -f -

          kubectl create configmap gym-config \
            --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -n gym-namespace --dry-run=client -o yaml | kubectl apply -f -

          echo "Verifying secrets and configmaps..."
          kubectl get secret gym-secret -n gym-namespace -o yaml
          kubectl get configmap gym-config -n gym-namespace -o yaml

      # Step 11: Apply Kubernetes Manifests (🚀 IMPORTANT: Remove configmap.yaml & secret.yaml)
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Step 12: Restart Deployment to Load Secrets
      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment gym-deployment -n gym-namespace

      # Step 13: Retrieve External IP of the Service
      - name: Retrieve External IP
        id: get_ip
        run: |
          echo "Waiting for LoadBalancer IP..."
          for i in {1..30}; do
            EXTERNAL_IP=$(kubectl get svc gym-service -n gym-namespace -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [ -n "$EXTERNAL_IP" ]; then
              echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
              echo "External IP: $EXTERNAL_IP"
              break
            fi
            echo "Attempt $i: External IP not assigned yet. Retrying in 10 seconds..."
            sleep 10
          done

          if [ -z "$EXTERNAL_IP" ]; then
            echo "Failed to retrieve External IP."
            exit 1
          fi

      # Step 14: Output the External IP
      - name: Output External IP
        run: |
          echo "The application is accessible at http://${{ env.EXTERNAL_IP }}"

      # Step 15: Push Updated Terraform State to NutzKiller/TF Repository
      - name: Push Updated Terraform State to NutzKiller/TF Repository
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          if [ -f terraform/terraform_state/terraform.tfstate ]; then
            cp terraform/terraform_state/terraform.tfstate TF/terraform_state/terraform.tfstate
            cd TF

            git config --global user.email "yuvalshmuely8@gmail.com"
            git config --global user.name "NutzKiller"

            # Pull latest changes before pushing
            git pull origin main --rebase || echo "Pull failed. Continuing with local changes."

            # Add updated Terraform state file
            git add terraform_state/terraform.tfstate

            # Commit changes if there are any, or create an empty commit if none
            git commit -m "Update Terraform state file" || git commit --allow-empty -m "Dummy commit to ensure sync"

            # Force push to ensure the push succeeds
            git push origin main --force
          else
            echo "No Terraform state file found to push. Skipping this step."
          fi
