name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Apply Terraform Configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TF_VAR_MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Wait for 300 seconds
        run: |
          echo "Waiting for 300 seconds..."
          sleep 300

      - name: Destroy Terraform Configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        working-directory: terraform
        run: |
          terraform destroy -auto-approve

      - name: Push Terraform State to GitHub
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        working-directory: terraform
        run: |
          git init
          git config --global user.email "yuvalshmuely8@gmail.com"
          git config --global user.name "NutzKiller"
          git remote add origin https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/NutzKiller/TF.git || true
          git fetch origin main || true
          git checkout -B main || true
          git pull origin main --allow-unrelated-histories --strategy-option ours || true
          git add terraform_state/terraform.tfstate
          git commit -m "Update Terraform state file after destroy" || true
          git push origin main --force
