name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Apply Terraform Configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Save Public IP
        run: |
          terraform output -raw public_ip > public_ip.txt
        working-directory: terraform

      - name: Upload Public IP
        uses: actions/upload-artifact@v3
        with:
          name: public-ip
          path: terraform/public_ip.txt

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Download Public IP
        uses: actions/download-artifact@v3
        with:
          name: public-ip
          path: terraform/

      - name: Wait for 5 minutes
        run: sleep 300

      - name: Terminate EC2 Instance
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=ip-address,Values=$(cat terraform/public_ip.txt)" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)
          if [ -n "$INSTANCE_ID" ]; then
            echo "Terminating instance $INSTANCE_ID..."
            aws ec2 terminate-instances --instance-ids $INSTANCE_ID
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID
            echo "Instance $INSTANCE_ID terminated."
          else
            echo "No instance found with the provided IP address."
          fi
