name: Cleanup DockerHub and Helm Tags

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to cleanup DockerHub and Helm tags'
        required: true
        default: 'no'

jobs:
  cleanup:
    if: ${{ github.event.inputs.confirm == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # --------------------------
      # 1) DockerHub Cleanup
      # --------------------------
      - name: Cleanup DockerHub repository
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          set -e
          echo "Logging in to DockerHub..."
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "'"$DOCKER_USERNAME"'", "password": "'"$DOCKER_PASSWORD"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
            echo "Failed to retrieve token"
            exit 1
          fi

          REPO="nutzkiller/gym"
          echo "Fetching tags for repository $REPO..."

          # Fetch up to 100 tags (adjust page_size if needed)
          TAGS=$(curl -s -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" \
            | jq -r '.results | sort_by(.last_updated) | reverse | .[].name')

          echo "All tags:"
          echo "$TAGS"

          # Keep only the latest 5 tags
          KEEP_TAGS=$(echo "$TAGS" | head -n 5)
          echo "Tags to keep (latest 5):"
          echo "$KEEP_TAGS"

          # Delete tags that are not in KEEP_TAGS
          for tag in $TAGS; do
            if echo "$KEEP_TAGS" | grep -qx "$tag"; then
              echo "Keeping tag: $tag"
            else
              echo "Deleting tag: $tag"
              curl -s -X DELETE -H "Authorization: JWT $TOKEN" \
                "https://hub.docker.com/v2/repositories/$REPO/tags/$tag/"
            fi
          done

          echo "DockerHub cleanup completed."

      # --------------------------
      # 2) Helm Git Tags Cleanup
      # --------------------------
      - name: Cleanup Helm Tags
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          set -e
          echo "Fetching Git tags for NutzKiller/helm repository..."

          # Get up to 100 tags from the Git references API
          tags=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/NutzKiller/helm/git/refs/tags?per_page=100")
          count=$(echo "$tags" | jq 'length')
          echo "Found $count tags"

          # Build an array of { ref, sha, date } for each tag
          tag_info_array=()
          for row in $(echo "$tags" | jq -r '.[] | @base64'); do
            _jq() {
              echo "$row" | base64 --decode | jq -r "$1"
            }
            ref=$(_jq '.ref')
            sha=$(_jq '.object.sha')

            # Fetch commit info to get its date
            commit_date=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/NutzKiller/helm/commits/$sha" \
              | jq -r '.commit.committer.date')

            # Store as a JSON object in an array
            tag_info_array+=("$(echo "{\"ref\":\"$ref\",\"sha\":\"$sha\",\"date\":\"$commit_date\"}")")
          done

          # Combine into a single JSON array
          tag_info_json=$(printf '%s\n' "${tag_info_array[@]}" | jq -s '.')

          # Sort by date descending
          sorted_tags=$(echo "$tag_info_json" | jq -r 'sort_by(.date) | reverse')

          # Keep only the newest 5
          keep_refs=$(echo "$sorted_tags" | jq -r '.[0:5].ref')
          all_refs=$(echo "$sorted_tags" | jq -r '.[].ref')

          echo "Tags to keep (newest 5):"
          echo "$keep_refs"

          # Delete tags that are not in keep_refs
          for ref in $all_refs; do
            if echo "$keep_refs" | grep -qx "$ref"; then
              echo "Keeping tag: $ref"
            else
              echo "Deleting tag: $ref"
              tag_name=$(echo "$ref" | sed 's#^refs/tags/##')
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/NutzKiller/helm/git/refs/tags/$tag_name"
            fi
          done

          echo "Helm tags cleanup completed."
