name: CD GCP Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy_gcp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Authenticate to GCP
        shell: bash
        run: |
          # Decode the Base64 secret back into JSON:
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY_B64 }}" | base64 -d | tr -d '\r' > gcp-keyfile.json

          gcloud auth activate-service-account --key-file=gcp-keyfile.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region ${{ secrets.GCP_REGION }}
          gcloud config set compute/zone ${{ secrets.GCP_ZONE }}

      - name: Terraform Init and Apply
        working-directory: terraform_gcp
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_zone: ${{ secrets.GCP_ZONE }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Output GCP IP
        working-directory: terraform_gcp
        run: |
          echo "Public IP of the instance:"
          terraform output instance_external_ip
