name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          VERSION=v1.0.${{ github.run_number }}
          docker build -t nutzkiller/gym:$VERSION .
          docker tag nutzkiller/gym:$VERSION nutzkiller/gym:latest

      - name: Push Docker image to Docker Hub
        run: |
          VERSION=v1.0.${{ github.run_number }}
          docker push nutzkiller/gym:$VERSION
          docker push nutzkiller/gym:latest

      - name: Log in to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "=== Updating and installing dependencies ==="
            sudo yum update -y
            # Install docker, python/pip, git, plus any needed libs
            sudo yum install -y docker python3 python3-pip python3-libs git

            echo "=== Starting & enabling Docker ==="
            sudo service docker start
            sudo systemctl enable docker

            echo "=== Checking if docker-compose is installed via pip ==="
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing docker-compose via pip..."
              sudo pip3 install --force-reinstall --upgrade docker-compose
            else
              echo "docker-compose is already installed."
            fi

            echo "=== Adding ec2-user to Docker group (optional) ==="
            sudo usermod -aG docker ec2-user || true

            echo "=== Logging in to Docker Hub on EC2 ==="
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

            echo "=== Pulling latest Docker image ==="
            docker pull nutzkiller/gym:latest

            echo "=== Stopping old container if exists ==="
            docker stop gym_app || true
            docker rm gym_app || true

            echo "=== Cloning or updating repo in /home/ec2-user/gym ==="
            if [ ! -d /home/ec2-user/gym ]; then
              # Clone if folder doesn't exist
              sudo mkdir -p /home/ec2-user
              cd /home/ec2-user
              sudo git clone https://github.com/NutzKiller/gym.git
              sudo chown -R ec2-user:ec2-user gym
            else
              # Pull latest changes if folder already exists
              cd /home/ec2-user/gym
              sudo git pull
              cd ..
            fi

            # Make sure ec2-user owns the gym folder
            sudo chown -R ec2-user:ec2-user /home/ec2-user/gym

            echo "=== Running docker-compose from the cloned repo ==="
            cd /home/ec2-user/gym

            # If your docker-compose.yml is in a subfolder, e.g. /home/ec2-user/gym/docker-compose.yml
            # then we are in the correct dir now. If it's deeper, cd there or adapt these commands.
            docker-compose pull
            docker-compose up -d

            echo "=== Waiting 10 seconds for the container to start ==="
            sleep 10

            echo "=== Checking if app responds on port 5000 ==="
            if curl -f http://localhost:5000; then
              echo "App is up and responding!"
            else
              echo "App not responding, deployment failed!"
              exit 1
            fi

            echo "=== Deployment complete! ==="
