name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          VERSION=v1.0.${{ github.run_number }}
          docker build --no-cache -t nutzkiller/gym:$VERSION .
          docker tag nutzkiller/gym:$VERSION nutzkiller/gym:latest

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker compose up -d  # Start containers
          echo "Waiting for application to start..."
          RETRIES=0
          MAX_RETRIES=24  # ~2 minutes if sleeping 5 seconds each
          until curl --fail --max-time 120 http://localhost:5000; do
            echo "Waiting for application to start..."
            sleep 5
            RETRIES=$((RETRIES+1))
            if [ $RETRIES -ge $MAX_RETRIES ]; then
              echo "Application failed to start in time."
              exit 1
            fi
          done
          echo "Application started successfully!"

      - name: Push Docker Image to Docker Hub
        run: |
          VERSION=v1.0.${{ github.run_number }}
          docker push nutzkiller/gym:$VERSION
          docker push nutzkiller/gym:latest

      # -----------------------------------------
      # Bump Helm Chart version BEFORE packaging
      # -----------------------------------------
      - name: Bump Helm Chart Version
        run: |
          CHART_FILE="gym-chart/Chart.yaml"
          echo "Current Chart.yaml version:"
          grep '^version:' $CHART_FILE || echo "No version line found!"

          # Extract current version (assuming line is "version: X.Y.Z")
          current_version=$(grep '^version:' $CHART_FILE | awk '{print $2}')
          
          # If current_version is empty or not found, fall back to "0.0.0"
          if [ -z "$current_version" ]; then
            current_version="0.0.0"
          fi

          # Bump the patch version (e.g. 1.2.3 -> 1.2.4)
          new_version=$(echo "$current_version" | awk -F. '{$NF += 1; print $1 "." $2 "." $3}' OFS='.')

          # Update Chart.yaml in-place with new version
          sed -i "s/^version:.*/version: $new_version/" "$CHART_FILE"

          echo "Updated Chart.yaml version to $new_version"

      # -------------------------------------------------------
      # Commit and push the updated Chart.yaml using MY_GITHUB_TOKEN
      # -------------------------------------------------------
      - name: Commit Updated Chart.yaml
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.email "yuvalshmuely8@gmail.com"
          git config --global user.name "NutzKiller"
          
          # Make sure we use our personal access token for pushing
          git remote set-url origin https://x-access-token:${MY_GITHUB_TOKEN}@github.com/NutzKiller/GYM-HELM.git
          
          git add gym-chart/Chart.yaml
          git commit -m "Bump Helm chart version to $new_version" || echo "No changes to commit"
          # Push to main or whichever branch you're on
          git push origin HEAD:main

      # -------------------------
      # Now we package the chart
      # -------------------------
      - name: Install Helm
        run: |
          curl -L https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz -o helm.tar.gz
          tar -xzvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Package Helm Chart
        run: |
          mkdir -p helm-repo
          helm package gym-chart --destination helm-repo
          ls -la helm-repo

      - name: Update Helm Repository Index
        run: |
          helm repo index helm-repo --url https://NutzKiller.github.io/helm

      - name: Publish Helm Chart to GitHub Pages Repository
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          # Configure Git with your identity
          git config --global user.email "yuvalshmuely8@gmail.com"
          git config --global user.name "NutzKiller"
          
          # Clone the helm repository using MY_GITHUB_TOKEN
          git clone https://x-access-token:${MY_GITHUB_TOKEN}@github.com/NutzKiller/helm.git helm-temp
          
          # Copy packaged charts and update the index
          cp -R helm-repo/* helm-temp/
          cd helm-temp
          helm repo index . --url https://NutzKiller.github.io/helm
          
          # Commit and push the changes
          git add .
          git commit -m "Update Helm charts for build ${{ github.run_number }}" || echo "No changes to commit"
          git push origin main
